/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWareraRouteImport } from './routes/app.warera'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppWareraMeRouteImport } from './routes/app.warera.me'
import { Route as AppWareraDashboardRouteImport } from './routes/app.warera.dashboard'
import { Route as AppWareraUsersIndexRouteImport } from './routes/app.warera.users.index'
import { Route as AppWareraRegionsIndexRouteImport } from './routes/app.warera.regions.index'
import { Route as AppWareraCountriesIndexRouteImport } from './routes/app.warera.countries.index'
import { Route as AppWareraCompaniesIndexRouteImport } from './routes/app.warera.companies.index'
import { Route as AppWareraUsersIdRouteImport } from './routes/app.warera.users.$id'
import { Route as AppWareraRegionsIdRouteImport } from './routes/app.warera.regions.$id'
import { Route as AppWareraCountriesIdRouteImport } from './routes/app.warera.countries.$id'
import { Route as AppWareraCompaniesIdRouteImport } from './routes/app.warera.companies.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWareraRoute = AppWareraRouteImport.update({
  id: '/warera',
  path: '/warera',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppWareraMeRoute = AppWareraMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppWareraRoute,
} as any)
const AppWareraDashboardRoute = AppWareraDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppWareraRoute,
} as any)
const AppWareraUsersIndexRoute = AppWareraUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppWareraRoute,
} as any)
const AppWareraRegionsIndexRoute = AppWareraRegionsIndexRouteImport.update({
  id: '/regions/',
  path: '/regions/',
  getParentRoute: () => AppWareraRoute,
} as any)
const AppWareraCountriesIndexRoute = AppWareraCountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => AppWareraRoute,
} as any)
const AppWareraCompaniesIndexRoute = AppWareraCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => AppWareraRoute,
} as any)
const AppWareraUsersIdRoute = AppWareraUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AppWareraRoute,
} as any)
const AppWareraRegionsIdRoute = AppWareraRegionsIdRouteImport.update({
  id: '/regions/$id',
  path: '/regions/$id',
  getParentRoute: () => AppWareraRoute,
} as any)
const AppWareraCountriesIdRoute = AppWareraCountriesIdRouteImport.update({
  id: '/countries/$id',
  path: '/countries/$id',
  getParentRoute: () => AppWareraRoute,
} as any)
const AppWareraCompaniesIdRoute = AppWareraCompaniesIdRouteImport.update({
  id: '/companies/$id',
  path: '/companies/$id',
  getParentRoute: () => AppWareraRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/warera': typeof AppWareraRouteWithChildren
  '/app/warera/dashboard': typeof AppWareraDashboardRoute
  '/app/warera/me': typeof AppWareraMeRoute
  '/app/warera/companies/$id': typeof AppWareraCompaniesIdRoute
  '/app/warera/countries/$id': typeof AppWareraCountriesIdRoute
  '/app/warera/regions/$id': typeof AppWareraRegionsIdRoute
  '/app/warera/users/$id': typeof AppWareraUsersIdRoute
  '/app/warera/companies/': typeof AppWareraCompaniesIndexRoute
  '/app/warera/countries/': typeof AppWareraCountriesIndexRoute
  '/app/warera/regions/': typeof AppWareraRegionsIndexRoute
  '/app/warera/users/': typeof AppWareraUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/warera': typeof AppWareraRouteWithChildren
  '/app/warera/dashboard': typeof AppWareraDashboardRoute
  '/app/warera/me': typeof AppWareraMeRoute
  '/app/warera/companies/$id': typeof AppWareraCompaniesIdRoute
  '/app/warera/countries/$id': typeof AppWareraCountriesIdRoute
  '/app/warera/regions/$id': typeof AppWareraRegionsIdRoute
  '/app/warera/users/$id': typeof AppWareraUsersIdRoute
  '/app/warera/companies': typeof AppWareraCompaniesIndexRoute
  '/app/warera/countries': typeof AppWareraCountriesIndexRoute
  '/app/warera/regions': typeof AppWareraRegionsIndexRoute
  '/app/warera/users': typeof AppWareraUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/warera': typeof AppWareraRouteWithChildren
  '/app/warera/dashboard': typeof AppWareraDashboardRoute
  '/app/warera/me': typeof AppWareraMeRoute
  '/app/warera/companies/$id': typeof AppWareraCompaniesIdRoute
  '/app/warera/countries/$id': typeof AppWareraCountriesIdRoute
  '/app/warera/regions/$id': typeof AppWareraRegionsIdRoute
  '/app/warera/users/$id': typeof AppWareraUsersIdRoute
  '/app/warera/companies/': typeof AppWareraCompaniesIndexRoute
  '/app/warera/countries/': typeof AppWareraCountriesIndexRoute
  '/app/warera/regions/': typeof AppWareraRegionsIndexRoute
  '/app/warera/users/': typeof AppWareraUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/admin'
    | '/app/dashboard'
    | '/app/settings'
    | '/app/warera'
    | '/app/warera/dashboard'
    | '/app/warera/me'
    | '/app/warera/companies/$id'
    | '/app/warera/countries/$id'
    | '/app/warera/regions/$id'
    | '/app/warera/users/$id'
    | '/app/warera/companies/'
    | '/app/warera/countries/'
    | '/app/warera/regions/'
    | '/app/warera/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/admin'
    | '/app/dashboard'
    | '/app/settings'
    | '/app/warera'
    | '/app/warera/dashboard'
    | '/app/warera/me'
    | '/app/warera/companies/$id'
    | '/app/warera/countries/$id'
    | '/app/warera/regions/$id'
    | '/app/warera/users/$id'
    | '/app/warera/companies'
    | '/app/warera/countries'
    | '/app/warera/regions'
    | '/app/warera/users'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/admin'
    | '/app/dashboard'
    | '/app/settings'
    | '/app/warera'
    | '/app/warera/dashboard'
    | '/app/warera/me'
    | '/app/warera/companies/$id'
    | '/app/warera/countries/$id'
    | '/app/warera/regions/$id'
    | '/app/warera/users/$id'
    | '/app/warera/companies/'
    | '/app/warera/countries/'
    | '/app/warera/regions/'
    | '/app/warera/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/warera': {
      id: '/app/warera'
      path: '/warera'
      fullPath: '/app/warera'
      preLoaderRoute: typeof AppWareraRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/warera/me': {
      id: '/app/warera/me'
      path: '/me'
      fullPath: '/app/warera/me'
      preLoaderRoute: typeof AppWareraMeRouteImport
      parentRoute: typeof AppWareraRoute
    }
    '/app/warera/dashboard': {
      id: '/app/warera/dashboard'
      path: '/dashboard'
      fullPath: '/app/warera/dashboard'
      preLoaderRoute: typeof AppWareraDashboardRouteImport
      parentRoute: typeof AppWareraRoute
    }
    '/app/warera/users/': {
      id: '/app/warera/users/'
      path: '/users'
      fullPath: '/app/warera/users/'
      preLoaderRoute: typeof AppWareraUsersIndexRouteImport
      parentRoute: typeof AppWareraRoute
    }
    '/app/warera/regions/': {
      id: '/app/warera/regions/'
      path: '/regions'
      fullPath: '/app/warera/regions/'
      preLoaderRoute: typeof AppWareraRegionsIndexRouteImport
      parentRoute: typeof AppWareraRoute
    }
    '/app/warera/countries/': {
      id: '/app/warera/countries/'
      path: '/countries'
      fullPath: '/app/warera/countries/'
      preLoaderRoute: typeof AppWareraCountriesIndexRouteImport
      parentRoute: typeof AppWareraRoute
    }
    '/app/warera/companies/': {
      id: '/app/warera/companies/'
      path: '/companies'
      fullPath: '/app/warera/companies/'
      preLoaderRoute: typeof AppWareraCompaniesIndexRouteImport
      parentRoute: typeof AppWareraRoute
    }
    '/app/warera/users/$id': {
      id: '/app/warera/users/$id'
      path: '/users/$id'
      fullPath: '/app/warera/users/$id'
      preLoaderRoute: typeof AppWareraUsersIdRouteImport
      parentRoute: typeof AppWareraRoute
    }
    '/app/warera/regions/$id': {
      id: '/app/warera/regions/$id'
      path: '/regions/$id'
      fullPath: '/app/warera/regions/$id'
      preLoaderRoute: typeof AppWareraRegionsIdRouteImport
      parentRoute: typeof AppWareraRoute
    }
    '/app/warera/countries/$id': {
      id: '/app/warera/countries/$id'
      path: '/countries/$id'
      fullPath: '/app/warera/countries/$id'
      preLoaderRoute: typeof AppWareraCountriesIdRouteImport
      parentRoute: typeof AppWareraRoute
    }
    '/app/warera/companies/$id': {
      id: '/app/warera/companies/$id'
      path: '/companies/$id'
      fullPath: '/app/warera/companies/$id'
      preLoaderRoute: typeof AppWareraCompaniesIdRouteImport
      parentRoute: typeof AppWareraRoute
    }
  }
}

interface AppWareraRouteChildren {
  AppWareraDashboardRoute: typeof AppWareraDashboardRoute
  AppWareraMeRoute: typeof AppWareraMeRoute
  AppWareraCompaniesIdRoute: typeof AppWareraCompaniesIdRoute
  AppWareraCountriesIdRoute: typeof AppWareraCountriesIdRoute
  AppWareraRegionsIdRoute: typeof AppWareraRegionsIdRoute
  AppWareraUsersIdRoute: typeof AppWareraUsersIdRoute
  AppWareraCompaniesIndexRoute: typeof AppWareraCompaniesIndexRoute
  AppWareraCountriesIndexRoute: typeof AppWareraCountriesIndexRoute
  AppWareraRegionsIndexRoute: typeof AppWareraRegionsIndexRoute
  AppWareraUsersIndexRoute: typeof AppWareraUsersIndexRoute
}

const AppWareraRouteChildren: AppWareraRouteChildren = {
  AppWareraDashboardRoute: AppWareraDashboardRoute,
  AppWareraMeRoute: AppWareraMeRoute,
  AppWareraCompaniesIdRoute: AppWareraCompaniesIdRoute,
  AppWareraCountriesIdRoute: AppWareraCountriesIdRoute,
  AppWareraRegionsIdRoute: AppWareraRegionsIdRoute,
  AppWareraUsersIdRoute: AppWareraUsersIdRoute,
  AppWareraCompaniesIndexRoute: AppWareraCompaniesIndexRoute,
  AppWareraCountriesIndexRoute: AppWareraCountriesIndexRoute,
  AppWareraRegionsIndexRoute: AppWareraRegionsIndexRoute,
  AppWareraUsersIndexRoute: AppWareraUsersIndexRoute,
}

const AppWareraRouteWithChildren = AppWareraRoute._addFileChildren(
  AppWareraRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWareraRoute: typeof AppWareraRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWareraRoute: AppWareraRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
