/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWareraRouteImport } from './routes/app.warera'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppWareraWorkRouteImport } from './routes/app.warera.work'
import { Route as AppWareraTransactionsRouteImport } from './routes/app.warera.transactions'
import { Route as AppWareraSearchRouteImport } from './routes/app.warera.search'
import { Route as AppWareraRankingsRouteImport } from './routes/app.warera.rankings'
import { Route as AppWareraMeRouteImport } from './routes/app.warera.me'
import { Route as AppWareraItemsRouteImport } from './routes/app.warera.items'
import { Route as AppWareraDashboardRouteImport } from './routes/app.warera.dashboard'
import { Route as AppWareraUsersIndexRouteImport } from './routes/app.warera.users.index'
import { Route as AppWareraRegionsIndexRouteImport } from './routes/app.warera.regions.index'
import { Route as AppWareraCountriesIndexRouteImport } from './routes/app.warera.countries.index'
import { Route as AppWareraCompaniesIndexRouteImport } from './routes/app.warera.companies.index'
import { Route as AppWareraBattlesIndexRouteImport } from './routes/app.warera.battles.index'
import { Route as AppWareraArticlesIndexRouteImport } from './routes/app.warera.articles.index'
import { Route as AppWareraUsersIdRouteImport } from './routes/app.warera.users.$id'
import { Route as AppWareraRegionsIdRouteImport } from './routes/app.warera.regions.$id'
import { Route as AppWareraCountriesIdRouteImport } from './routes/app.warera.countries.$id'
import { Route as AppWareraCompaniesIdRouteImport } from './routes/app.warera.companies.$id'
import { Route as AppWareraBattlesIdRouteImport } from './routes/app.warera.battles.$id'
import { Route as AppWareraArticlesIdRouteImport } from './routes/app.warera.articles.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWareraRoute = AppWareraRouteImport.update({
  id: '/warera',
  path: '/warera',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppWareraWorkRoute = AppWareraWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AppWareraRoute,
} as any)
const AppWareraTransactionsRoute = AppWareraTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppWareraRoute,
} as any)
const AppWareraSearchRoute = AppWareraSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppWareraRoute,
} as any)
const AppWareraRankingsRoute = AppWareraRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AppWareraRoute,
} as any)
const AppWareraMeRoute = AppWareraMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppWareraRoute,
} as any)
const AppWareraItemsRoute = AppWareraItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AppWareraRoute,
} as any)
const AppWareraDashboardRoute = AppWareraDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppWareraRoute,
} as any)
const AppWareraUsersIndexRoute = AppWareraUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppWareraRoute,
} as any)
const AppWareraRegionsIndexRoute = AppWareraRegionsIndexRouteImport.update({
  id: '/regions/',
  path: '/regions/',
  getParentRoute: () => AppWareraRoute,
} as any)
const AppWareraCountriesIndexRoute = AppWareraCountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => AppWareraRoute,
} as any)
const AppWareraCompaniesIndexRoute = AppWareraCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => AppWareraRoute,
} as any)
const AppWareraBattlesIndexRoute = AppWareraBattlesIndexRouteImport.update({
  id: '/battles/',
  path: '/battles/',
  getParentRoute: () => AppWareraRoute,
} as any)
const AppWareraArticlesIndexRoute = AppWareraArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => AppWareraRoute,
} as any)
const AppWareraUsersIdRoute = AppWareraUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AppWareraRoute,
} as any)
const AppWareraRegionsIdRoute = AppWareraRegionsIdRouteImport.update({
  id: '/regions/$id',
  path: '/regions/$id',
  getParentRoute: () => AppWareraRoute,
} as any)
const AppWareraCountriesIdRoute = AppWareraCountriesIdRouteImport.update({
  id: '/countries/$id',
  path: '/countries/$id',
  getParentRoute: () => AppWareraRoute,
} as any)
const AppWareraCompaniesIdRoute = AppWareraCompaniesIdRouteImport.update({
  id: '/companies/$id',
  path: '/companies/$id',
  getParentRoute: () => AppWareraRoute,
} as any)
const AppWareraBattlesIdRoute = AppWareraBattlesIdRouteImport.update({
  id: '/battles/$id',
  path: '/battles/$id',
  getParentRoute: () => AppWareraRoute,
} as any)
const AppWareraArticlesIdRoute = AppWareraArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => AppWareraRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/warera': typeof AppWareraRouteWithChildren
  '/app/warera/dashboard': typeof AppWareraDashboardRoute
  '/app/warera/items': typeof AppWareraItemsRoute
  '/app/warera/me': typeof AppWareraMeRoute
  '/app/warera/rankings': typeof AppWareraRankingsRoute
  '/app/warera/search': typeof AppWareraSearchRoute
  '/app/warera/transactions': typeof AppWareraTransactionsRoute
  '/app/warera/work': typeof AppWareraWorkRoute
  '/app/warera/articles/$id': typeof AppWareraArticlesIdRoute
  '/app/warera/battles/$id': typeof AppWareraBattlesIdRoute
  '/app/warera/companies/$id': typeof AppWareraCompaniesIdRoute
  '/app/warera/countries/$id': typeof AppWareraCountriesIdRoute
  '/app/warera/regions/$id': typeof AppWareraRegionsIdRoute
  '/app/warera/users/$id': typeof AppWareraUsersIdRoute
  '/app/warera/articles/': typeof AppWareraArticlesIndexRoute
  '/app/warera/battles/': typeof AppWareraBattlesIndexRoute
  '/app/warera/companies/': typeof AppWareraCompaniesIndexRoute
  '/app/warera/countries/': typeof AppWareraCountriesIndexRoute
  '/app/warera/regions/': typeof AppWareraRegionsIndexRoute
  '/app/warera/users/': typeof AppWareraUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/warera': typeof AppWareraRouteWithChildren
  '/app/warera/dashboard': typeof AppWareraDashboardRoute
  '/app/warera/items': typeof AppWareraItemsRoute
  '/app/warera/me': typeof AppWareraMeRoute
  '/app/warera/rankings': typeof AppWareraRankingsRoute
  '/app/warera/search': typeof AppWareraSearchRoute
  '/app/warera/transactions': typeof AppWareraTransactionsRoute
  '/app/warera/work': typeof AppWareraWorkRoute
  '/app/warera/articles/$id': typeof AppWareraArticlesIdRoute
  '/app/warera/battles/$id': typeof AppWareraBattlesIdRoute
  '/app/warera/companies/$id': typeof AppWareraCompaniesIdRoute
  '/app/warera/countries/$id': typeof AppWareraCountriesIdRoute
  '/app/warera/regions/$id': typeof AppWareraRegionsIdRoute
  '/app/warera/users/$id': typeof AppWareraUsersIdRoute
  '/app/warera/articles': typeof AppWareraArticlesIndexRoute
  '/app/warera/battles': typeof AppWareraBattlesIndexRoute
  '/app/warera/companies': typeof AppWareraCompaniesIndexRoute
  '/app/warera/countries': typeof AppWareraCountriesIndexRoute
  '/app/warera/regions': typeof AppWareraRegionsIndexRoute
  '/app/warera/users': typeof AppWareraUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/warera': typeof AppWareraRouteWithChildren
  '/app/warera/dashboard': typeof AppWareraDashboardRoute
  '/app/warera/items': typeof AppWareraItemsRoute
  '/app/warera/me': typeof AppWareraMeRoute
  '/app/warera/rankings': typeof AppWareraRankingsRoute
  '/app/warera/search': typeof AppWareraSearchRoute
  '/app/warera/transactions': typeof AppWareraTransactionsRoute
  '/app/warera/work': typeof AppWareraWorkRoute
  '/app/warera/articles/$id': typeof AppWareraArticlesIdRoute
  '/app/warera/battles/$id': typeof AppWareraBattlesIdRoute
  '/app/warera/companies/$id': typeof AppWareraCompaniesIdRoute
  '/app/warera/countries/$id': typeof AppWareraCountriesIdRoute
  '/app/warera/regions/$id': typeof AppWareraRegionsIdRoute
  '/app/warera/users/$id': typeof AppWareraUsersIdRoute
  '/app/warera/articles/': typeof AppWareraArticlesIndexRoute
  '/app/warera/battles/': typeof AppWareraBattlesIndexRoute
  '/app/warera/companies/': typeof AppWareraCompaniesIndexRoute
  '/app/warera/countries/': typeof AppWareraCountriesIndexRoute
  '/app/warera/regions/': typeof AppWareraRegionsIndexRoute
  '/app/warera/users/': typeof AppWareraUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/admin'
    | '/app/dashboard'
    | '/app/settings'
    | '/app/warera'
    | '/app/warera/dashboard'
    | '/app/warera/items'
    | '/app/warera/me'
    | '/app/warera/rankings'
    | '/app/warera/search'
    | '/app/warera/transactions'
    | '/app/warera/work'
    | '/app/warera/articles/$id'
    | '/app/warera/battles/$id'
    | '/app/warera/companies/$id'
    | '/app/warera/countries/$id'
    | '/app/warera/regions/$id'
    | '/app/warera/users/$id'
    | '/app/warera/articles/'
    | '/app/warera/battles/'
    | '/app/warera/companies/'
    | '/app/warera/countries/'
    | '/app/warera/regions/'
    | '/app/warera/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/admin'
    | '/app/dashboard'
    | '/app/settings'
    | '/app/warera'
    | '/app/warera/dashboard'
    | '/app/warera/items'
    | '/app/warera/me'
    | '/app/warera/rankings'
    | '/app/warera/search'
    | '/app/warera/transactions'
    | '/app/warera/work'
    | '/app/warera/articles/$id'
    | '/app/warera/battles/$id'
    | '/app/warera/companies/$id'
    | '/app/warera/countries/$id'
    | '/app/warera/regions/$id'
    | '/app/warera/users/$id'
    | '/app/warera/articles'
    | '/app/warera/battles'
    | '/app/warera/companies'
    | '/app/warera/countries'
    | '/app/warera/regions'
    | '/app/warera/users'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/admin'
    | '/app/dashboard'
    | '/app/settings'
    | '/app/warera'
    | '/app/warera/dashboard'
    | '/app/warera/items'
    | '/app/warera/me'
    | '/app/warera/rankings'
    | '/app/warera/search'
    | '/app/warera/transactions'
    | '/app/warera/work'
    | '/app/warera/articles/$id'
    | '/app/warera/battles/$id'
    | '/app/warera/companies/$id'
    | '/app/warera/countries/$id'
    | '/app/warera/regions/$id'
    | '/app/warera/users/$id'
    | '/app/warera/articles/'
    | '/app/warera/battles/'
    | '/app/warera/companies/'
    | '/app/warera/countries/'
    | '/app/warera/regions/'
    | '/app/warera/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/warera': {
      id: '/app/warera'
      path: '/warera'
      fullPath: '/app/warera'
      preLoaderRoute: typeof AppWareraRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/warera/work': {
      id: '/app/warera/work'
      path: '/work'
      fullPath: '/app/warera/work'
      preLoaderRoute: typeof AppWareraWorkRouteImport
      parentRoute: typeof AppWareraRoute
    }
    '/app/warera/transactions': {
      id: '/app/warera/transactions'
      path: '/transactions'
      fullPath: '/app/warera/transactions'
      preLoaderRoute: typeof AppWareraTransactionsRouteImport
      parentRoute: typeof AppWareraRoute
    }
    '/app/warera/search': {
      id: '/app/warera/search'
      path: '/search'
      fullPath: '/app/warera/search'
      preLoaderRoute: typeof AppWareraSearchRouteImport
      parentRoute: typeof AppWareraRoute
    }
    '/app/warera/rankings': {
      id: '/app/warera/rankings'
      path: '/rankings'
      fullPath: '/app/warera/rankings'
      preLoaderRoute: typeof AppWareraRankingsRouteImport
      parentRoute: typeof AppWareraRoute
    }
    '/app/warera/me': {
      id: '/app/warera/me'
      path: '/me'
      fullPath: '/app/warera/me'
      preLoaderRoute: typeof AppWareraMeRouteImport
      parentRoute: typeof AppWareraRoute
    }
    '/app/warera/items': {
      id: '/app/warera/items'
      path: '/items'
      fullPath: '/app/warera/items'
      preLoaderRoute: typeof AppWareraItemsRouteImport
      parentRoute: typeof AppWareraRoute
    }
    '/app/warera/dashboard': {
      id: '/app/warera/dashboard'
      path: '/dashboard'
      fullPath: '/app/warera/dashboard'
      preLoaderRoute: typeof AppWareraDashboardRouteImport
      parentRoute: typeof AppWareraRoute
    }
    '/app/warera/users/': {
      id: '/app/warera/users/'
      path: '/users'
      fullPath: '/app/warera/users/'
      preLoaderRoute: typeof AppWareraUsersIndexRouteImport
      parentRoute: typeof AppWareraRoute
    }
    '/app/warera/regions/': {
      id: '/app/warera/regions/'
      path: '/regions'
      fullPath: '/app/warera/regions/'
      preLoaderRoute: typeof AppWareraRegionsIndexRouteImport
      parentRoute: typeof AppWareraRoute
    }
    '/app/warera/countries/': {
      id: '/app/warera/countries/'
      path: '/countries'
      fullPath: '/app/warera/countries/'
      preLoaderRoute: typeof AppWareraCountriesIndexRouteImport
      parentRoute: typeof AppWareraRoute
    }
    '/app/warera/companies/': {
      id: '/app/warera/companies/'
      path: '/companies'
      fullPath: '/app/warera/companies/'
      preLoaderRoute: typeof AppWareraCompaniesIndexRouteImport
      parentRoute: typeof AppWareraRoute
    }
    '/app/warera/battles/': {
      id: '/app/warera/battles/'
      path: '/battles'
      fullPath: '/app/warera/battles/'
      preLoaderRoute: typeof AppWareraBattlesIndexRouteImport
      parentRoute: typeof AppWareraRoute
    }
    '/app/warera/articles/': {
      id: '/app/warera/articles/'
      path: '/articles'
      fullPath: '/app/warera/articles/'
      preLoaderRoute: typeof AppWareraArticlesIndexRouteImport
      parentRoute: typeof AppWareraRoute
    }
    '/app/warera/users/$id': {
      id: '/app/warera/users/$id'
      path: '/users/$id'
      fullPath: '/app/warera/users/$id'
      preLoaderRoute: typeof AppWareraUsersIdRouteImport
      parentRoute: typeof AppWareraRoute
    }
    '/app/warera/regions/$id': {
      id: '/app/warera/regions/$id'
      path: '/regions/$id'
      fullPath: '/app/warera/regions/$id'
      preLoaderRoute: typeof AppWareraRegionsIdRouteImport
      parentRoute: typeof AppWareraRoute
    }
    '/app/warera/countries/$id': {
      id: '/app/warera/countries/$id'
      path: '/countries/$id'
      fullPath: '/app/warera/countries/$id'
      preLoaderRoute: typeof AppWareraCountriesIdRouteImport
      parentRoute: typeof AppWareraRoute
    }
    '/app/warera/companies/$id': {
      id: '/app/warera/companies/$id'
      path: '/companies/$id'
      fullPath: '/app/warera/companies/$id'
      preLoaderRoute: typeof AppWareraCompaniesIdRouteImport
      parentRoute: typeof AppWareraRoute
    }
    '/app/warera/battles/$id': {
      id: '/app/warera/battles/$id'
      path: '/battles/$id'
      fullPath: '/app/warera/battles/$id'
      preLoaderRoute: typeof AppWareraBattlesIdRouteImport
      parentRoute: typeof AppWareraRoute
    }
    '/app/warera/articles/$id': {
      id: '/app/warera/articles/$id'
      path: '/articles/$id'
      fullPath: '/app/warera/articles/$id'
      preLoaderRoute: typeof AppWareraArticlesIdRouteImport
      parentRoute: typeof AppWareraRoute
    }
  }
}

interface AppWareraRouteChildren {
  AppWareraDashboardRoute: typeof AppWareraDashboardRoute
  AppWareraItemsRoute: typeof AppWareraItemsRoute
  AppWareraMeRoute: typeof AppWareraMeRoute
  AppWareraRankingsRoute: typeof AppWareraRankingsRoute
  AppWareraSearchRoute: typeof AppWareraSearchRoute
  AppWareraTransactionsRoute: typeof AppWareraTransactionsRoute
  AppWareraWorkRoute: typeof AppWareraWorkRoute
  AppWareraArticlesIdRoute: typeof AppWareraArticlesIdRoute
  AppWareraBattlesIdRoute: typeof AppWareraBattlesIdRoute
  AppWareraCompaniesIdRoute: typeof AppWareraCompaniesIdRoute
  AppWareraCountriesIdRoute: typeof AppWareraCountriesIdRoute
  AppWareraRegionsIdRoute: typeof AppWareraRegionsIdRoute
  AppWareraUsersIdRoute: typeof AppWareraUsersIdRoute
  AppWareraArticlesIndexRoute: typeof AppWareraArticlesIndexRoute
  AppWareraBattlesIndexRoute: typeof AppWareraBattlesIndexRoute
  AppWareraCompaniesIndexRoute: typeof AppWareraCompaniesIndexRoute
  AppWareraCountriesIndexRoute: typeof AppWareraCountriesIndexRoute
  AppWareraRegionsIndexRoute: typeof AppWareraRegionsIndexRoute
  AppWareraUsersIndexRoute: typeof AppWareraUsersIndexRoute
}

const AppWareraRouteChildren: AppWareraRouteChildren = {
  AppWareraDashboardRoute: AppWareraDashboardRoute,
  AppWareraItemsRoute: AppWareraItemsRoute,
  AppWareraMeRoute: AppWareraMeRoute,
  AppWareraRankingsRoute: AppWareraRankingsRoute,
  AppWareraSearchRoute: AppWareraSearchRoute,
  AppWareraTransactionsRoute: AppWareraTransactionsRoute,
  AppWareraWorkRoute: AppWareraWorkRoute,
  AppWareraArticlesIdRoute: AppWareraArticlesIdRoute,
  AppWareraBattlesIdRoute: AppWareraBattlesIdRoute,
  AppWareraCompaniesIdRoute: AppWareraCompaniesIdRoute,
  AppWareraCountriesIdRoute: AppWareraCountriesIdRoute,
  AppWareraRegionsIdRoute: AppWareraRegionsIdRoute,
  AppWareraUsersIdRoute: AppWareraUsersIdRoute,
  AppWareraArticlesIndexRoute: AppWareraArticlesIndexRoute,
  AppWareraBattlesIndexRoute: AppWareraBattlesIndexRoute,
  AppWareraCompaniesIndexRoute: AppWareraCompaniesIndexRoute,
  AppWareraCountriesIndexRoute: AppWareraCountriesIndexRoute,
  AppWareraRegionsIndexRoute: AppWareraRegionsIndexRoute,
  AppWareraUsersIndexRoute: AppWareraUsersIndexRoute,
}

const AppWareraRouteWithChildren = AppWareraRoute._addFileChildren(
  AppWareraRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWareraRoute: typeof AppWareraRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWareraRoute: AppWareraRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
